version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: bookdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Somphors123
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  springboot-app:
    build: .
    container_name: springboot-api
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bookdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Somphors123
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
